name: 'Saplings - Component types'
description: 'Configuration for Saplings component types.'
type: 'Site'
install:
  # Core.
  # - example
  # Contrib.
  - block_content
  - block_field
  - nomarkup
  - saplings-component-base
  - viewsreference
config:
  import:
    # Core.
    # module_name:
    #  - one.config.name
    # Contrib.
    # block_field
