name: 'Saplings - Component types'
description: 'Installs Saplings component types.'
type: 'Site'
recipes:
  - saplings-component-base
  - saplings-editorial
install:
  # Core.
  - block_content
  - ckeditor5
  - frontend_editing
  - link
  - media
  - media_library
  - text
  # Contrib.
  - block_field
  - ds
  - element_class_formatter
  - entity_reference_revisions
  - field_group
  - nomarkup
  - paragraphs
  - paragraphs_edit
  - ui_patterns_field_formatters
  - viewsreference
