name: 'Saplings - Component types'
description: 'Installs Saplings component types.'
type: 'Site'
recipes:
  - saplings-component-base
install:
  # Core.
  - block_content
  - media
  - media_library
  - text
  # Contrib.
  - block_field
  - bootstrap_layout_classes
  - ds
  - element_class_formatter
  - entity_reference_revisions
  - nomarkup
  - paragraphs
  - viewsreference
