name: 'Saplings - Component types'
description: 'Configuration for Saplings component types.'
type: 'Site'
recipes:
  - saplings-component-base
  - saplings-content-base
  - saplings-theme
install:
  # Core.
  # - example
  # Contrib.
  - block_content
  - block_field
  - ds
  - nomarkup
  - media
  - viewsreference
config:
  import:
    # Core.
    # module_name:
    #  - one.config.name
    # Contrib.
    # block_field
